-- =========================================================
-- AHMAD & YARA WEDDING DATABASE — UPDATED SCHEMA / MIGRATION
-- =========================================================
-- This version changes the database to exactly what you requested:
--   RSVP:    id, guest_name, created_at
--   Comments:id, guest_name, message, created_at
-- IDs are simple integers: 1, 2, 3, ...
-- Guests can submit, but cannot directly read/update/delete table rows.
--
-- IMPORTANT:
-- Because you already have data in the current database, run this file
-- in Supabase SQL Editor to migrate the existing tables without deleting
-- the submitted records.
-- =========================================================

-- ---------------------------------------------------------
-- 1. Remove old function versions first
-- ---------------------------------------------------------
drop function if exists public.submit_rsvp(text, text);
drop function if exists public.submit_rsvp(text);
drop function if exists public.submit_comment(text, text, text);
drop function if exists public.submit_comment(text, text);

-- ---------------------------------------------------------
-- 2. RSVP table
--    Convert UUID id -> integer id and remove attending/language
-- ---------------------------------------------------------

-- Add a new integer identity column. Existing rows receive 1, 2, 3, ...
alter table public.rsvps
    add column if not exists id_new bigint generated by default as identity;

-- Remove the old UUID id and replace it with the integer id.
alter table public.rsvps drop column if exists id;
alter table public.rsvps rename column id_new to id;
alter table public.rsvps add primary key (id);

-- These columns are no longer needed.
alter table public.rsvps drop column if exists attending;
alter table public.rsvps drop column if exists language;

-- ---------------------------------------------------------
-- 3. Comments table
--    Convert UUID id -> integer id and remove language
-- ---------------------------------------------------------

alter table public.comments
    add column if not exists id_new bigint generated by default as identity;

alter table public.comments drop column if exists id;
alter table public.comments rename column id_new to id;
alter table public.comments add primary key (id);

alter table public.comments drop column if exists language;

-- ---------------------------------------------------------
-- 4. Keep RLS enabled and remove direct table access
-- ---------------------------------------------------------
alter table public.rsvps enable row level security;
alter table public.comments enable row level security;

revoke all on table public.rsvps from anon, authenticated;
revoke all on table public.comments from anon, authenticated;

-- ---------------------------------------------------------
-- 5. New RSVP submission function
-- ---------------------------------------------------------
create or replace function public.submit_rsvp(
    p_guest_name text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if char_length(btrim(coalesce(p_guest_name, ''))) < 2
       or char_length(btrim(coalesce(p_guest_name, ''))) > 100 then
        raise exception 'Please enter a valid name.';
    end if;

    insert into public.rsvps (guest_name)
    values (btrim(p_guest_name));
end;
$$;

-- ---------------------------------------------------------
-- 6. New comment submission function
-- ---------------------------------------------------------
create or replace function public.submit_comment(
    p_guest_name text,
    p_message text
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
    if char_length(btrim(coalesce(p_guest_name, ''))) < 2
       or char_length(btrim(coalesce(p_guest_name, ''))) > 100 then
        raise exception 'Please enter a valid name.';
    end if;

    if char_length(btrim(coalesce(p_message, ''))) < 1
       or char_length(btrim(coalesce(p_message, ''))) > 1000 then
        raise exception 'Please enter a message.';
    end if;

    insert into public.comments (guest_name, message)
    values (btrim(p_guest_name), btrim(p_message));
end;
$$;

-- ---------------------------------------------------------
-- 7. Function permissions
-- ---------------------------------------------------------
revoke all on function public.submit_rsvp(text) from public;
revoke all on function public.submit_rsvp(text) from anon;
revoke all on function public.submit_rsvp(text) from authenticated;

revoke all on function public.submit_comment(text, text) from public;
revoke all on function public.submit_comment(text, text) from anon;
revoke all on function public.submit_comment(text, text) from authenticated;

grant execute on function public.submit_rsvp(text) to anon;
grant execute on function public.submit_comment(text, text) to anon;

-- =========================================================
-- FINAL STRUCTURE
-- =========================================================
-- rsvps:    id | guest_name | created_at
-- comments: id | guest_name | message | created_at
-- =========================================================
